//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealogikal.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeologikalDTREntities : DbContext
    {
        public DeologikalDTREntities()
            : base("name=DeologikalDTREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtrRecords> dtrRecords { get; set; }
        public virtual DbSet<employeeInfo> employeeInfo { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<userAccount> userAccount { get; set; }
        public virtual DbSet<vw_Role> vw_Role { get; set; }
    }
}
